Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.synced_folder "../uploads", "/uploads"
 config.vm.define :test1 do |test1|
 end
end